spring:
  application:
    name: heranca-hibernate
  #SPRING DATA
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

  #CONFIG SWAGGER
springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  servlet:
    context-path: /heranca